apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: mindx-app
type: Opaque
stringData:
  OIDC_CLIENT_ID: "mindx-onboarding"
  OIDC_CLIENT_SECRET: "cHJldmVudGJvdW5kYmF0dHJlZWV4cGxvcmVjZWxsbmVydm91c3ZhcG9ydGhhbnN0ZWU="
  JWT_SECRET: "3lb0YxBsKaCjqb0GusG7OJsn7xpSSvTF"
  ACCESS_TOKEN_SECRET: "Cy5xVbdq6b9BJ4v9wlcgXxCMjhfAUmlk"
  REFRESH_TOKEN_SECRET: "SWRsxGVlacCJyBb63r7BGEeftUpdSqZO"
  REDIS_PASSWORD: "2XHk4JdHALClbyQ537fsoSeSBSEMywYC"
