apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: mindx-app
data:
  NODE_ENV: "production"
  PORT: "3000"
  FRONTEND_URL: "https://hieunh01.mindx.edu.vn"
  MINDX_ISSUER: "https://id.mindx.edu.vn"
  MINDX_REDIRECT_URI: "https://hieunh01.mindx.edu.vn/api/auth/callback"
  REDIS_HOST: "redis-18224.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com"
  REDIS_PORT: "18224"
  GOOGLE_REDIRECT_URI: "https://hieunh01.mindx.edu.vn/api/auth/google/callback"
  POSTGRES_HOST: "mindx-onboarding-postgres.postgres.database.azure.com"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "mindxadmin"
  POSTGRES_DB_NAME: "postgres"
